### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by cdeil** [tisimst/mcerp#16]
The last mcerp release was 0.11 from 2014:

https://pypi.org/project/mcerp/#history

There's no more open issues, and mcerp master is Python 3 compatible.

@tisimst @paul-freeman - If you have any points that should be done, please comment here or file an issue.

Otherwise, tomorrow I plan to:

- Update the changelog and README and polish the docs a little bit
- Release mcerp 0.12 on PyPI

**Comment by paul-freeman** [comment]
I don't have anything else to add at the moment.

I have been hosting my fork as a conda package, as well. So, if you ever want to set that up, I can provide the meta.yaml file for that.

**Comment by cdeil** [comment]
> I have been hosting my fork as a conda package, as well. So, if you ever want to set that up, I can provide the meta.yaml file for that.

I would not set this up, since `mcerp` is a pure-Python package with very simple dependencies. There is conda-forge of course, that would be the way to go to build and distribute conda packages, but I'm not sure it's really useful / worth the effort in this case.

**Comment by cdeil** [comment]
I've finally made the v0.12 release:

- `git tag v0.12` resulting in https://github.com/tisimst/mcerp/releases
- sdist release on PyPI: https://pypi.org/project/mcerp/0.12/

I've also added a page https://github.com/tisimst/mcerp/blob/master/doc/contribute.rst with the commands how to do a release at the bottom.

The installation instructions in the README and docs are also updated to say that now Python 2.7 and 3.5+ is supported (that's what we test in continuous integration, earlier versions might or might not work, but those have approximately zero users anyways).

@paul-freeman - Maybe you could try `pip install -U mcerp` and see if everything works for you?
And if so, add a note from your Python 3 fork README pointing back to this package, saying that it should be used and updated moving forward?
