### ISSUE TITLE
sample from distribution

### ISSUE THREAD

**Issue by MalteEbner** [tisimst/mcerp#20]
How can I sample from any mcerp distribution? Specifically I want to sample a PERT-distributed random number.

**Comment by tisimst** [comment]
Do you want to access the samples already created or use the object to generate new samples? If the first, all samples that were created when the object was can be accessed from the _mcpts property of the object. If the latter, there’s no easy way to do this except for maybe creating new objects, which will generate a whole new set of samples, but nothing to generate them on the fly.
